[package]
name = "aoc_2022_5_b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"
scan_fmt = "0.2.6"
support = { path = "../support" }
